### ISSUE TITLE
libAppIndicator not included

### ISSUE THREAD

**Issue by Ironlenny** [flathub/org.gpodder.gpodder#8]
I'm using flatpak 1.0.1 on KDE Neon 5.13. When I run gPodder I get this error:
```
1536001558.628318 [gpodder.extensions] ERROR: Cannot load ubuntu_appindicator from /app/share/gpodder/extensions/ubuntu_appindicator.py: No module named 'appindicator'
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/gpodder/extensions.py", line 260, in set_enabled
    self.load_extension()
  File "/app/lib/python3.5/site-packages/gpodder/extensions.py", line 303, in load_extension
    (extension, 'r', imp.PY_SOURCE))
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/app/share/gpodder/extensions/ubuntu_appindicator.py", line 19, in <module>
    import appindicator
ImportError: No module named 'appindicator'
```

It looks like it's not included with the flatpak. I see it included with other ones. I have libappindicator and the python module installed on my system.

**Comment by TingPing** [comment]
I don't *think* that will fix it @nedrichards. `import appindicator` implies ancient pygtk bindings, I'd be surprised if it even works since GPodder moved to pygobject.

**Comment by nedrichards** [comment]
Oh, right - hrm.

**Comment by Ironlenny** [comment]
So this bug should be moved upstream?

**Comment by Ironlenny** [comment]
gpodder/gpodder#537

**Comment by Ironlenny** [comment]
https://github.com/gpodder/gpodder/commit/a44b92446b55632a1ba9aab4b3e0a700c450e434

**Comment by nedrichards** [comment]
Sweet! Looking forward to integrating the new release.

**Comment by nedrichards** [comment]
New release integrated https://github.com/flathub/org.gpodder.gpodder/commit/177c1dfb519012d1b9bdf89607cdc1112c7a2bbb
